// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: streaming_rpc_meta.proto

package com.baidu.brpc.protocol;

public final class StreamingRpcProto {
  private StreamingRpcProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code brpc.FrameType}
   */
  public enum FrameType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FRAME_TYPE_UNKNOWN = 0;</code>
     */
    FRAME_TYPE_UNKNOWN(0, 0),
    /**
     * <code>FRAME_TYPE_RST = 1;</code>
     */
    FRAME_TYPE_RST(1, 1),
    /**
     * <code>FRAME_TYPE_CLOSE = 2;</code>
     */
    FRAME_TYPE_CLOSE(2, 2),
    /**
     * <code>FRAME_TYPE_DATA = 3;</code>
     */
    FRAME_TYPE_DATA(3, 3),
    /**
     * <code>FRAME_TYPE_FEEDBACK = 4;</code>
     */
    FRAME_TYPE_FEEDBACK(4, 4),
    ;

    /**
     * <code>FRAME_TYPE_UNKNOWN = 0;</code>
     */
    public static final int FRAME_TYPE_UNKNOWN_VALUE = 0;
    /**
     * <code>FRAME_TYPE_RST = 1;</code>
     */
    public static final int FRAME_TYPE_RST_VALUE = 1;
    /**
     * <code>FRAME_TYPE_CLOSE = 2;</code>
     */
    public static final int FRAME_TYPE_CLOSE_VALUE = 2;
    /**
     * <code>FRAME_TYPE_DATA = 3;</code>
     */
    public static final int FRAME_TYPE_DATA_VALUE = 3;
    /**
     * <code>FRAME_TYPE_FEEDBACK = 4;</code>
     */
    public static final int FRAME_TYPE_FEEDBACK_VALUE = 4;


    public final int getNumber() { return value; }

    public static FrameType valueOf(int value) {
      switch (value) {
        case 0: return FRAME_TYPE_UNKNOWN;
        case 1: return FRAME_TYPE_RST;
        case 2: return FRAME_TYPE_CLOSE;
        case 3: return FRAME_TYPE_DATA;
        case 4: return FRAME_TYPE_FEEDBACK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FrameType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<FrameType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FrameType>() {
            public FrameType findValueByNumber(int number) {
              return FrameType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.baidu.brpc.protocol.StreamingRpcProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final FrameType[] VALUES = values();

    public static FrameType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private FrameType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:brpc.FrameType)
  }

  public interface StreamSettingsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 stream_id = 1;
    /**
     * <code>required int64 stream_id = 1;</code>
     */
    boolean hasStreamId();
    /**
     * <code>required int64 stream_id = 1;</code>
     */
    long getStreamId();

    // optional bool need_feedback = 2 [default = false];
    /**
     * <code>optional bool need_feedback = 2 [default = false];</code>
     */
    boolean hasNeedFeedback();
    /**
     * <code>optional bool need_feedback = 2 [default = false];</code>
     */
    boolean getNeedFeedback();

    // optional bool writable = 3 [default = false];
    /**
     * <code>optional bool writable = 3 [default = false];</code>
     */
    boolean hasWritable();
    /**
     * <code>optional bool writable = 3 [default = false];</code>
     */
    boolean getWritable();
  }
  /**
   * Protobuf type {@code brpc.StreamSettings}
   */
  public static final class StreamSettings extends
      com.google.protobuf.GeneratedMessage
      implements StreamSettingsOrBuilder {
    // Use StreamSettings.newBuilder() to construct.
    private StreamSettings(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StreamSettings(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StreamSettings defaultInstance;
    public static StreamSettings getDefaultInstance() {
      return defaultInstance;
    }

    public StreamSettings getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StreamSettings(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              streamId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              needFeedback_ = input.readBool();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              writable_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.baidu.brpc.protocol.StreamingRpcProto.internal_static_brpc_StreamSettings_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.baidu.brpc.protocol.StreamingRpcProto.internal_static_brpc_StreamSettings_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.baidu.brpc.protocol.StreamingRpcProto.StreamSettings.class, com.baidu.brpc.protocol.StreamingRpcProto.StreamSettings.Builder.class);
    }

    public static com.google.protobuf.Parser<StreamSettings> PARSER =
        new com.google.protobuf.AbstractParser<StreamSettings>() {
      public StreamSettings parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StreamSettings(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StreamSettings> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 stream_id = 1;
    public static final int STREAM_ID_FIELD_NUMBER = 1;
    private long streamId_;
    /**
     * <code>required int64 stream_id = 1;</code>
     */
    public boolean hasStreamId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 stream_id = 1;</code>
     */
    public long getStreamId() {
      return streamId_;
    }

    // optional bool need_feedback = 2 [default = false];
    public static final int NEED_FEEDBACK_FIELD_NUMBER = 2;
    private boolean needFeedback_;
    /**
     * <code>optional bool need_feedback = 2 [default = false];</code>
     */
    public boolean hasNeedFeedback() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool need_feedback = 2 [default = false];</code>
     */
    public boolean getNeedFeedback() {
      return needFeedback_;
    }

    // optional bool writable = 3 [default = false];
    public static final int WRITABLE_FIELD_NUMBER = 3;
    private boolean writable_;
    /**
     * <code>optional bool writable = 3 [default = false];</code>
     */
    public boolean hasWritable() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool writable = 3 [default = false];</code>
     */
    public boolean getWritable() {
      return writable_;
    }

    private void initFields() {
      streamId_ = 0L;
      needFeedback_ = false;
      writable_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasStreamId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, streamId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, needFeedback_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, writable_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, streamId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, needFeedback_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, writable_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.baidu.brpc.protocol.StreamingRpcProto.StreamSettings parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.brpc.protocol.StreamingRpcProto.StreamSettings parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.brpc.protocol.StreamingRpcProto.StreamSettings parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.brpc.protocol.StreamingRpcProto.StreamSettings parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.brpc.protocol.StreamingRpcProto.StreamSettings parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.brpc.protocol.StreamingRpcProto.StreamSettings parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.baidu.brpc.protocol.StreamingRpcProto.StreamSettings parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.baidu.brpc.protocol.StreamingRpcProto.StreamSettings parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.baidu.brpc.protocol.StreamingRpcProto.StreamSettings parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.brpc.protocol.StreamingRpcProto.StreamSettings parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.baidu.brpc.protocol.StreamingRpcProto.StreamSettings prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code brpc.StreamSettings}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.baidu.brpc.protocol.StreamingRpcProto.StreamSettingsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.baidu.brpc.protocol.StreamingRpcProto.internal_static_brpc_StreamSettings_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.baidu.brpc.protocol.StreamingRpcProto.internal_static_brpc_StreamSettings_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.baidu.brpc.protocol.StreamingRpcProto.StreamSettings.class, com.baidu.brpc.protocol.StreamingRpcProto.StreamSettings.Builder.class);
      }

      // Construct using com.baidu.brpc.protocol.StreamingRpcProto.StreamSettings.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        streamId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        needFeedback_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        writable_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.baidu.brpc.protocol.StreamingRpcProto.internal_static_brpc_StreamSettings_descriptor;
      }

      public com.baidu.brpc.protocol.StreamingRpcProto.StreamSettings getDefaultInstanceForType() {
        return com.baidu.brpc.protocol.StreamingRpcProto.StreamSettings.getDefaultInstance();
      }

      public com.baidu.brpc.protocol.StreamingRpcProto.StreamSettings build() {
        com.baidu.brpc.protocol.StreamingRpcProto.StreamSettings result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.baidu.brpc.protocol.StreamingRpcProto.StreamSettings buildPartial() {
        com.baidu.brpc.protocol.StreamingRpcProto.StreamSettings result = new com.baidu.brpc.protocol.StreamingRpcProto.StreamSettings(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.streamId_ = streamId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.needFeedback_ = needFeedback_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.writable_ = writable_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.baidu.brpc.protocol.StreamingRpcProto.StreamSettings) {
          return mergeFrom((com.baidu.brpc.protocol.StreamingRpcProto.StreamSettings)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.baidu.brpc.protocol.StreamingRpcProto.StreamSettings other) {
        if (other == com.baidu.brpc.protocol.StreamingRpcProto.StreamSettings.getDefaultInstance()) return this;
        if (other.hasStreamId()) {
          setStreamId(other.getStreamId());
        }
        if (other.hasNeedFeedback()) {
          setNeedFeedback(other.getNeedFeedback());
        }
        if (other.hasWritable()) {
          setWritable(other.getWritable());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStreamId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.baidu.brpc.protocol.StreamingRpcProto.StreamSettings parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.baidu.brpc.protocol.StreamingRpcProto.StreamSettings) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 stream_id = 1;
      private long streamId_ ;
      /**
       * <code>required int64 stream_id = 1;</code>
       */
      public boolean hasStreamId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 stream_id = 1;</code>
       */
      public long getStreamId() {
        return streamId_;
      }
      /**
       * <code>required int64 stream_id = 1;</code>
       */
      public Builder setStreamId(long value) {
        bitField0_ |= 0x00000001;
        streamId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 stream_id = 1;</code>
       */
      public Builder clearStreamId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        streamId_ = 0L;
        onChanged();
        return this;
      }

      // optional bool need_feedback = 2 [default = false];
      private boolean needFeedback_ ;
      /**
       * <code>optional bool need_feedback = 2 [default = false];</code>
       */
      public boolean hasNeedFeedback() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool need_feedback = 2 [default = false];</code>
       */
      public boolean getNeedFeedback() {
        return needFeedback_;
      }
      /**
       * <code>optional bool need_feedback = 2 [default = false];</code>
       */
      public Builder setNeedFeedback(boolean value) {
        bitField0_ |= 0x00000002;
        needFeedback_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool need_feedback = 2 [default = false];</code>
       */
      public Builder clearNeedFeedback() {
        bitField0_ = (bitField0_ & ~0x00000002);
        needFeedback_ = false;
        onChanged();
        return this;
      }

      // optional bool writable = 3 [default = false];
      private boolean writable_ ;
      /**
       * <code>optional bool writable = 3 [default = false];</code>
       */
      public boolean hasWritable() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool writable = 3 [default = false];</code>
       */
      public boolean getWritable() {
        return writable_;
      }
      /**
       * <code>optional bool writable = 3 [default = false];</code>
       */
      public Builder setWritable(boolean value) {
        bitField0_ |= 0x00000004;
        writable_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool writable = 3 [default = false];</code>
       */
      public Builder clearWritable() {
        bitField0_ = (bitField0_ & ~0x00000004);
        writable_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:brpc.StreamSettings)
    }

    static {
      defaultInstance = new StreamSettings(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:brpc.StreamSettings)
  }

  public interface StreamFrameMetaOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 stream_id = 1;
    /**
     * <code>required int64 stream_id = 1;</code>
     */
    boolean hasStreamId();
    /**
     * <code>required int64 stream_id = 1;</code>
     */
    long getStreamId();

    // optional int64 source_stream_id = 2;
    /**
     * <code>optional int64 source_stream_id = 2;</code>
     */
    boolean hasSourceStreamId();
    /**
     * <code>optional int64 source_stream_id = 2;</code>
     */
    long getSourceStreamId();

    // optional .brpc.FrameType frame_type = 3;
    /**
     * <code>optional .brpc.FrameType frame_type = 3;</code>
     */
    boolean hasFrameType();
    /**
     * <code>optional .brpc.FrameType frame_type = 3;</code>
     */
    com.baidu.brpc.protocol.StreamingRpcProto.FrameType getFrameType();

    // optional bool has_continuation = 4;
    /**
     * <code>optional bool has_continuation = 4;</code>
     */
    boolean hasHasContinuation();
    /**
     * <code>optional bool has_continuation = 4;</code>
     */
    boolean getHasContinuation();

    // optional .brpc.Feedback feedback = 5;
    /**
     * <code>optional .brpc.Feedback feedback = 5;</code>
     */
    boolean hasFeedback();
    /**
     * <code>optional .brpc.Feedback feedback = 5;</code>
     */
    com.baidu.brpc.protocol.StreamingRpcProto.Feedback getFeedback();
    /**
     * <code>optional .brpc.Feedback feedback = 5;</code>
     */
    com.baidu.brpc.protocol.StreamingRpcProto.FeedbackOrBuilder getFeedbackOrBuilder();
  }
  /**
   * Protobuf type {@code brpc.StreamFrameMeta}
   */
  public static final class StreamFrameMeta extends
      com.google.protobuf.GeneratedMessage
      implements StreamFrameMetaOrBuilder {
    // Use StreamFrameMeta.newBuilder() to construct.
    private StreamFrameMeta(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StreamFrameMeta(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StreamFrameMeta defaultInstance;
    public static StreamFrameMeta getDefaultInstance() {
      return defaultInstance;
    }

    public StreamFrameMeta getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StreamFrameMeta(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              streamId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sourceStreamId_ = input.readInt64();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.baidu.brpc.protocol.StreamingRpcProto.FrameType value = com.baidu.brpc.protocol.StreamingRpcProto.FrameType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                frameType_ = value;
              }
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              hasContinuation_ = input.readBool();
              break;
            }
            case 42: {
              com.baidu.brpc.protocol.StreamingRpcProto.Feedback.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = feedback_.toBuilder();
              }
              feedback_ = input.readMessage(com.baidu.brpc.protocol.StreamingRpcProto.Feedback.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(feedback_);
                feedback_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.baidu.brpc.protocol.StreamingRpcProto.internal_static_brpc_StreamFrameMeta_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.baidu.brpc.protocol.StreamingRpcProto.internal_static_brpc_StreamFrameMeta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.baidu.brpc.protocol.StreamingRpcProto.StreamFrameMeta.class, com.baidu.brpc.protocol.StreamingRpcProto.StreamFrameMeta.Builder.class);
    }

    public static com.google.protobuf.Parser<StreamFrameMeta> PARSER =
        new com.google.protobuf.AbstractParser<StreamFrameMeta>() {
      public StreamFrameMeta parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StreamFrameMeta(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StreamFrameMeta> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 stream_id = 1;
    public static final int STREAM_ID_FIELD_NUMBER = 1;
    private long streamId_;
    /**
     * <code>required int64 stream_id = 1;</code>
     */
    public boolean hasStreamId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 stream_id = 1;</code>
     */
    public long getStreamId() {
      return streamId_;
    }

    // optional int64 source_stream_id = 2;
    public static final int SOURCE_STREAM_ID_FIELD_NUMBER = 2;
    private long sourceStreamId_;
    /**
     * <code>optional int64 source_stream_id = 2;</code>
     */
    public boolean hasSourceStreamId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 source_stream_id = 2;</code>
     */
    public long getSourceStreamId() {
      return sourceStreamId_;
    }

    // optional .brpc.FrameType frame_type = 3;
    public static final int FRAME_TYPE_FIELD_NUMBER = 3;
    private com.baidu.brpc.protocol.StreamingRpcProto.FrameType frameType_;
    /**
     * <code>optional .brpc.FrameType frame_type = 3;</code>
     */
    public boolean hasFrameType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .brpc.FrameType frame_type = 3;</code>
     */
    public com.baidu.brpc.protocol.StreamingRpcProto.FrameType getFrameType() {
      return frameType_;
    }

    // optional bool has_continuation = 4;
    public static final int HAS_CONTINUATION_FIELD_NUMBER = 4;
    private boolean hasContinuation_;
    /**
     * <code>optional bool has_continuation = 4;</code>
     */
    public boolean hasHasContinuation() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool has_continuation = 4;</code>
     */
    public boolean getHasContinuation() {
      return hasContinuation_;
    }

    // optional .brpc.Feedback feedback = 5;
    public static final int FEEDBACK_FIELD_NUMBER = 5;
    private com.baidu.brpc.protocol.StreamingRpcProto.Feedback feedback_;
    /**
     * <code>optional .brpc.Feedback feedback = 5;</code>
     */
    public boolean hasFeedback() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .brpc.Feedback feedback = 5;</code>
     */
    public com.baidu.brpc.protocol.StreamingRpcProto.Feedback getFeedback() {
      return feedback_;
    }
    /**
     * <code>optional .brpc.Feedback feedback = 5;</code>
     */
    public com.baidu.brpc.protocol.StreamingRpcProto.FeedbackOrBuilder getFeedbackOrBuilder() {
      return feedback_;
    }

    private void initFields() {
      streamId_ = 0L;
      sourceStreamId_ = 0L;
      frameType_ = com.baidu.brpc.protocol.StreamingRpcProto.FrameType.FRAME_TYPE_UNKNOWN;
      hasContinuation_ = false;
      feedback_ = com.baidu.brpc.protocol.StreamingRpcProto.Feedback.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasStreamId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, streamId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, sourceStreamId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, frameType_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, hasContinuation_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, feedback_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, streamId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, sourceStreamId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, frameType_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, hasContinuation_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, feedback_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.baidu.brpc.protocol.StreamingRpcProto.StreamFrameMeta parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.brpc.protocol.StreamingRpcProto.StreamFrameMeta parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.brpc.protocol.StreamingRpcProto.StreamFrameMeta parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.brpc.protocol.StreamingRpcProto.StreamFrameMeta parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.brpc.protocol.StreamingRpcProto.StreamFrameMeta parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.brpc.protocol.StreamingRpcProto.StreamFrameMeta parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.baidu.brpc.protocol.StreamingRpcProto.StreamFrameMeta parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.baidu.brpc.protocol.StreamingRpcProto.StreamFrameMeta parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.baidu.brpc.protocol.StreamingRpcProto.StreamFrameMeta parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.brpc.protocol.StreamingRpcProto.StreamFrameMeta parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.baidu.brpc.protocol.StreamingRpcProto.StreamFrameMeta prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code brpc.StreamFrameMeta}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.baidu.brpc.protocol.StreamingRpcProto.StreamFrameMetaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.baidu.brpc.protocol.StreamingRpcProto.internal_static_brpc_StreamFrameMeta_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.baidu.brpc.protocol.StreamingRpcProto.internal_static_brpc_StreamFrameMeta_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.baidu.brpc.protocol.StreamingRpcProto.StreamFrameMeta.class, com.baidu.brpc.protocol.StreamingRpcProto.StreamFrameMeta.Builder.class);
      }

      // Construct using com.baidu.brpc.protocol.StreamingRpcProto.StreamFrameMeta.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFeedbackFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        streamId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        sourceStreamId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        frameType_ = com.baidu.brpc.protocol.StreamingRpcProto.FrameType.FRAME_TYPE_UNKNOWN;
        bitField0_ = (bitField0_ & ~0x00000004);
        hasContinuation_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (feedbackBuilder_ == null) {
          feedback_ = com.baidu.brpc.protocol.StreamingRpcProto.Feedback.getDefaultInstance();
        } else {
          feedbackBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.baidu.brpc.protocol.StreamingRpcProto.internal_static_brpc_StreamFrameMeta_descriptor;
      }

      public com.baidu.brpc.protocol.StreamingRpcProto.StreamFrameMeta getDefaultInstanceForType() {
        return com.baidu.brpc.protocol.StreamingRpcProto.StreamFrameMeta.getDefaultInstance();
      }

      public com.baidu.brpc.protocol.StreamingRpcProto.StreamFrameMeta build() {
        com.baidu.brpc.protocol.StreamingRpcProto.StreamFrameMeta result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.baidu.brpc.protocol.StreamingRpcProto.StreamFrameMeta buildPartial() {
        com.baidu.brpc.protocol.StreamingRpcProto.StreamFrameMeta result = new com.baidu.brpc.protocol.StreamingRpcProto.StreamFrameMeta(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.streamId_ = streamId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sourceStreamId_ = sourceStreamId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.frameType_ = frameType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.hasContinuation_ = hasContinuation_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (feedbackBuilder_ == null) {
          result.feedback_ = feedback_;
        } else {
          result.feedback_ = feedbackBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.baidu.brpc.protocol.StreamingRpcProto.StreamFrameMeta) {
          return mergeFrom((com.baidu.brpc.protocol.StreamingRpcProto.StreamFrameMeta)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.baidu.brpc.protocol.StreamingRpcProto.StreamFrameMeta other) {
        if (other == com.baidu.brpc.protocol.StreamingRpcProto.StreamFrameMeta.getDefaultInstance()) return this;
        if (other.hasStreamId()) {
          setStreamId(other.getStreamId());
        }
        if (other.hasSourceStreamId()) {
          setSourceStreamId(other.getSourceStreamId());
        }
        if (other.hasFrameType()) {
          setFrameType(other.getFrameType());
        }
        if (other.hasHasContinuation()) {
          setHasContinuation(other.getHasContinuation());
        }
        if (other.hasFeedback()) {
          mergeFeedback(other.getFeedback());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStreamId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.baidu.brpc.protocol.StreamingRpcProto.StreamFrameMeta parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.baidu.brpc.protocol.StreamingRpcProto.StreamFrameMeta) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 stream_id = 1;
      private long streamId_ ;
      /**
       * <code>required int64 stream_id = 1;</code>
       */
      public boolean hasStreamId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 stream_id = 1;</code>
       */
      public long getStreamId() {
        return streamId_;
      }
      /**
       * <code>required int64 stream_id = 1;</code>
       */
      public Builder setStreamId(long value) {
        bitField0_ |= 0x00000001;
        streamId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 stream_id = 1;</code>
       */
      public Builder clearStreamId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        streamId_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 source_stream_id = 2;
      private long sourceStreamId_ ;
      /**
       * <code>optional int64 source_stream_id = 2;</code>
       */
      public boolean hasSourceStreamId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 source_stream_id = 2;</code>
       */
      public long getSourceStreamId() {
        return sourceStreamId_;
      }
      /**
       * <code>optional int64 source_stream_id = 2;</code>
       */
      public Builder setSourceStreamId(long value) {
        bitField0_ |= 0x00000002;
        sourceStreamId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 source_stream_id = 2;</code>
       */
      public Builder clearSourceStreamId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sourceStreamId_ = 0L;
        onChanged();
        return this;
      }

      // optional .brpc.FrameType frame_type = 3;
      private com.baidu.brpc.protocol.StreamingRpcProto.FrameType frameType_ = com.baidu.brpc.protocol.StreamingRpcProto.FrameType.FRAME_TYPE_UNKNOWN;
      /**
       * <code>optional .brpc.FrameType frame_type = 3;</code>
       */
      public boolean hasFrameType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .brpc.FrameType frame_type = 3;</code>
       */
      public com.baidu.brpc.protocol.StreamingRpcProto.FrameType getFrameType() {
        return frameType_;
      }
      /**
       * <code>optional .brpc.FrameType frame_type = 3;</code>
       */
      public Builder setFrameType(com.baidu.brpc.protocol.StreamingRpcProto.FrameType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        frameType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .brpc.FrameType frame_type = 3;</code>
       */
      public Builder clearFrameType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        frameType_ = com.baidu.brpc.protocol.StreamingRpcProto.FrameType.FRAME_TYPE_UNKNOWN;
        onChanged();
        return this;
      }

      // optional bool has_continuation = 4;
      private boolean hasContinuation_ ;
      /**
       * <code>optional bool has_continuation = 4;</code>
       */
      public boolean hasHasContinuation() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bool has_continuation = 4;</code>
       */
      public boolean getHasContinuation() {
        return hasContinuation_;
      }
      /**
       * <code>optional bool has_continuation = 4;</code>
       */
      public Builder setHasContinuation(boolean value) {
        bitField0_ |= 0x00000008;
        hasContinuation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool has_continuation = 4;</code>
       */
      public Builder clearHasContinuation() {
        bitField0_ = (bitField0_ & ~0x00000008);
        hasContinuation_ = false;
        onChanged();
        return this;
      }

      // optional .brpc.Feedback feedback = 5;
      private com.baidu.brpc.protocol.StreamingRpcProto.Feedback feedback_ = com.baidu.brpc.protocol.StreamingRpcProto.Feedback.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.baidu.brpc.protocol.StreamingRpcProto.Feedback, com.baidu.brpc.protocol.StreamingRpcProto.Feedback.Builder, com.baidu.brpc.protocol.StreamingRpcProto.FeedbackOrBuilder> feedbackBuilder_;
      /**
       * <code>optional .brpc.Feedback feedback = 5;</code>
       */
      public boolean hasFeedback() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .brpc.Feedback feedback = 5;</code>
       */
      public com.baidu.brpc.protocol.StreamingRpcProto.Feedback getFeedback() {
        if (feedbackBuilder_ == null) {
          return feedback_;
        } else {
          return feedbackBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .brpc.Feedback feedback = 5;</code>
       */
      public Builder setFeedback(com.baidu.brpc.protocol.StreamingRpcProto.Feedback value) {
        if (feedbackBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          feedback_ = value;
          onChanged();
        } else {
          feedbackBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .brpc.Feedback feedback = 5;</code>
       */
      public Builder setFeedback(
          com.baidu.brpc.protocol.StreamingRpcProto.Feedback.Builder builderForValue) {
        if (feedbackBuilder_ == null) {
          feedback_ = builderForValue.build();
          onChanged();
        } else {
          feedbackBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .brpc.Feedback feedback = 5;</code>
       */
      public Builder mergeFeedback(com.baidu.brpc.protocol.StreamingRpcProto.Feedback value) {
        if (feedbackBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              feedback_ != com.baidu.brpc.protocol.StreamingRpcProto.Feedback.getDefaultInstance()) {
            feedback_ =
              com.baidu.brpc.protocol.StreamingRpcProto.Feedback.newBuilder(feedback_).mergeFrom(value).buildPartial();
          } else {
            feedback_ = value;
          }
          onChanged();
        } else {
          feedbackBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .brpc.Feedback feedback = 5;</code>
       */
      public Builder clearFeedback() {
        if (feedbackBuilder_ == null) {
          feedback_ = com.baidu.brpc.protocol.StreamingRpcProto.Feedback.getDefaultInstance();
          onChanged();
        } else {
          feedbackBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .brpc.Feedback feedback = 5;</code>
       */
      public com.baidu.brpc.protocol.StreamingRpcProto.Feedback.Builder getFeedbackBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getFeedbackFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .brpc.Feedback feedback = 5;</code>
       */
      public com.baidu.brpc.protocol.StreamingRpcProto.FeedbackOrBuilder getFeedbackOrBuilder() {
        if (feedbackBuilder_ != null) {
          return feedbackBuilder_.getMessageOrBuilder();
        } else {
          return feedback_;
        }
      }
      /**
       * <code>optional .brpc.Feedback feedback = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.baidu.brpc.protocol.StreamingRpcProto.Feedback, com.baidu.brpc.protocol.StreamingRpcProto.Feedback.Builder, com.baidu.brpc.protocol.StreamingRpcProto.FeedbackOrBuilder> 
          getFeedbackFieldBuilder() {
        if (feedbackBuilder_ == null) {
          feedbackBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.baidu.brpc.protocol.StreamingRpcProto.Feedback, com.baidu.brpc.protocol.StreamingRpcProto.Feedback.Builder, com.baidu.brpc.protocol.StreamingRpcProto.FeedbackOrBuilder>(
                  feedback_,
                  getParentForChildren(),
                  isClean());
          feedback_ = null;
        }
        return feedbackBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:brpc.StreamFrameMeta)
    }

    static {
      defaultInstance = new StreamFrameMeta(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:brpc.StreamFrameMeta)
  }

  public interface FeedbackOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 consumed_size = 1;
    /**
     * <code>optional int64 consumed_size = 1;</code>
     */
    boolean hasConsumedSize();
    /**
     * <code>optional int64 consumed_size = 1;</code>
     */
    long getConsumedSize();
  }
  /**
   * Protobuf type {@code brpc.Feedback}
   */
  public static final class Feedback extends
      com.google.protobuf.GeneratedMessage
      implements FeedbackOrBuilder {
    // Use Feedback.newBuilder() to construct.
    private Feedback(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Feedback(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Feedback defaultInstance;
    public static Feedback getDefaultInstance() {
      return defaultInstance;
    }

    public Feedback getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Feedback(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              consumedSize_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.baidu.brpc.protocol.StreamingRpcProto.internal_static_brpc_Feedback_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.baidu.brpc.protocol.StreamingRpcProto.internal_static_brpc_Feedback_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.baidu.brpc.protocol.StreamingRpcProto.Feedback.class, com.baidu.brpc.protocol.StreamingRpcProto.Feedback.Builder.class);
    }

    public static com.google.protobuf.Parser<Feedback> PARSER =
        new com.google.protobuf.AbstractParser<Feedback>() {
      public Feedback parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Feedback(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Feedback> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 consumed_size = 1;
    public static final int CONSUMED_SIZE_FIELD_NUMBER = 1;
    private long consumedSize_;
    /**
     * <code>optional int64 consumed_size = 1;</code>
     */
    public boolean hasConsumedSize() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 consumed_size = 1;</code>
     */
    public long getConsumedSize() {
      return consumedSize_;
    }

    private void initFields() {
      consumedSize_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, consumedSize_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, consumedSize_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.baidu.brpc.protocol.StreamingRpcProto.Feedback parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.brpc.protocol.StreamingRpcProto.Feedback parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.brpc.protocol.StreamingRpcProto.Feedback parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.brpc.protocol.StreamingRpcProto.Feedback parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.brpc.protocol.StreamingRpcProto.Feedback parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.brpc.protocol.StreamingRpcProto.Feedback parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.baidu.brpc.protocol.StreamingRpcProto.Feedback parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.baidu.brpc.protocol.StreamingRpcProto.Feedback parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.baidu.brpc.protocol.StreamingRpcProto.Feedback parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.brpc.protocol.StreamingRpcProto.Feedback parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.baidu.brpc.protocol.StreamingRpcProto.Feedback prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code brpc.Feedback}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.baidu.brpc.protocol.StreamingRpcProto.FeedbackOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.baidu.brpc.protocol.StreamingRpcProto.internal_static_brpc_Feedback_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.baidu.brpc.protocol.StreamingRpcProto.internal_static_brpc_Feedback_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.baidu.brpc.protocol.StreamingRpcProto.Feedback.class, com.baidu.brpc.protocol.StreamingRpcProto.Feedback.Builder.class);
      }

      // Construct using com.baidu.brpc.protocol.StreamingRpcProto.Feedback.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        consumedSize_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.baidu.brpc.protocol.StreamingRpcProto.internal_static_brpc_Feedback_descriptor;
      }

      public com.baidu.brpc.protocol.StreamingRpcProto.Feedback getDefaultInstanceForType() {
        return com.baidu.brpc.protocol.StreamingRpcProto.Feedback.getDefaultInstance();
      }

      public com.baidu.brpc.protocol.StreamingRpcProto.Feedback build() {
        com.baidu.brpc.protocol.StreamingRpcProto.Feedback result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.baidu.brpc.protocol.StreamingRpcProto.Feedback buildPartial() {
        com.baidu.brpc.protocol.StreamingRpcProto.Feedback result = new com.baidu.brpc.protocol.StreamingRpcProto.Feedback(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.consumedSize_ = consumedSize_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.baidu.brpc.protocol.StreamingRpcProto.Feedback) {
          return mergeFrom((com.baidu.brpc.protocol.StreamingRpcProto.Feedback)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.baidu.brpc.protocol.StreamingRpcProto.Feedback other) {
        if (other == com.baidu.brpc.protocol.StreamingRpcProto.Feedback.getDefaultInstance()) return this;
        if (other.hasConsumedSize()) {
          setConsumedSize(other.getConsumedSize());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.baidu.brpc.protocol.StreamingRpcProto.Feedback parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.baidu.brpc.protocol.StreamingRpcProto.Feedback) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 consumed_size = 1;
      private long consumedSize_ ;
      /**
       * <code>optional int64 consumed_size = 1;</code>
       */
      public boolean hasConsumedSize() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 consumed_size = 1;</code>
       */
      public long getConsumedSize() {
        return consumedSize_;
      }
      /**
       * <code>optional int64 consumed_size = 1;</code>
       */
      public Builder setConsumedSize(long value) {
        bitField0_ |= 0x00000001;
        consumedSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 consumed_size = 1;</code>
       */
      public Builder clearConsumedSize() {
        bitField0_ = (bitField0_ & ~0x00000001);
        consumedSize_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:brpc.Feedback)
    }

    static {
      defaultInstance = new Feedback(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:brpc.Feedback)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_brpc_StreamSettings_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_brpc_StreamSettings_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_brpc_StreamFrameMeta_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_brpc_StreamFrameMeta_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_brpc_Feedback_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_brpc_Feedback_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030streaming_rpc_meta.proto\022\004brpc\032\roption" +
      "s.proto\"Z\n\016StreamSettings\022\021\n\tstream_id\030\001" +
      " \002(\003\022\034\n\rneed_feedback\030\002 \001(\010:\005false\022\027\n\010wr" +
      "itable\030\003 \001(\010:\005false\"\237\001\n\017StreamFrameMeta\022" +
      "\021\n\tstream_id\030\001 \002(\003\022\030\n\020source_stream_id\030\002" +
      " \001(\003\022#\n\nframe_type\030\003 \001(\0162\017.brpc.FrameTyp" +
      "e\022\030\n\020has_continuation\030\004 \001(\010\022 \n\010feedback\030" +
      "\005 \001(\0132\016.brpc.Feedback\"!\n\010Feedback\022\025\n\rcon" +
      "sumed_size\030\001 \001(\003*{\n\tFrameType\022\026\n\022FRAME_T" +
      "YPE_UNKNOWN\020\000\022\022\n\016FRAME_TYPE_RST\020\001\022\024\n\020FRA",
      "ME_TYPE_CLOSE\020\002\022\023\n\017FRAME_TYPE_DATA\020\003\022\027\n\023" +
      "FRAME_TYPE_FEEDBACK\020\004B,\n\027com.baidu.brpc." +
      "protocolB\021StreamingRpcProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_brpc_StreamSettings_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_brpc_StreamSettings_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_brpc_StreamSettings_descriptor,
              new java.lang.String[] { "StreamId", "NeedFeedback", "Writable", });
          internal_static_brpc_StreamFrameMeta_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_brpc_StreamFrameMeta_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_brpc_StreamFrameMeta_descriptor,
              new java.lang.String[] { "StreamId", "SourceStreamId", "FrameType", "HasContinuation", "Feedback", });
          internal_static_brpc_Feedback_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_brpc_Feedback_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_brpc_Feedback_descriptor,
              new java.lang.String[] { "ConsumedSize", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.baidu.brpc.protocol.Options.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
